### ISSUE TITLE
body size

### ISSUE THREAD

**Issue by navidAbbasian** [navidAbbasian/PersoanlWebSite#1]
i cant find what is the problem
site has horizontal scroll and it must remove

**Comment by Rava-milad** [comment]
box-sizing: border-box;
add this class to universal selector example `*{
box-sizing: border-box;
}`

**Comment by navidAbbasian** [comment]
> 

Thanks for your answer, kiss on your bald head

**Comment by navidAbbasian** [comment]
i fix it with `
html, body {
    max-width: 100%;
    overflow-x: hidden;
}`
